### PR TITLE
fix typos for midi_uart0

### PR DESCRIPTION
**Pull request by okyeron**

### CODE REVIEW

**Comment by rppicomidi** [comment]
@okyeron Thanks for this! I coded for a second UART but never tested it because I only needed one. Have you verified the second UART is working as expected?

**Comment by okyeron** [comment]
Have not tested yet*, but plan to later tonight I think. I'm trying to set this up with an Adafruit Feather RP2040 and best I can tell they're using UART0 as default TX/RX

(* I wired up my midi breakout board wrong and blew the vreg, so gotta swap that out)

**Comment by okyeron** [comment]
Is this also an error?

https://github.com/rppicomidi/midi_uart_lib/blob/0f5a4b4fd506cbe00d6b9c212961e913c015eb23/midi_uart_lib.c#L129

and should be `on_midi_uart0_irq`?

**Comment by rppicomidi** [comment]
Good find. Looks like an error to me. Thank you.

**Review by rppicomidi — COMMENTED** [review]
@okyeron It looks like I can merge your pull request, but I don't have time to test it. Please let me know when you have tested this and if it solves your issues, I will merge it.

**Comment by okyeron** [comment]
I wasn't able to get this to work on the Feather but will try again on my pico board.

**Comment by rppicomidi** [comment]
@okyeron It occurs to me that if you are trying to use this library with tinyusb or any other code that calls `printf()` functions, you may be running into conflicts because by default, UART0 is a debug console UART. If, at the end of the day, you can't make your system work, and if your project has PIO available, you may want to consider using this [pio_midi_uart_lib](https://github.com/rppicomidi/pio_midi_uart_lib) instead (I just pushed it up and only tested it with one UART so far, so please report issues if you try it).

**Comment by rppicomidi** [comment]
@okyeron I finally got around to testing your changes on my hardware. Sorry for the delay. They are correct. Thank you for your efforts.

**Pull request merged**
